### ISSUE TITLE
pyproject.toml

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#106]
The current documentation for PROTEUS has information on which packages need to be installed. This could be made easier by having a `requirements.txt` file. We could then simply run: `conda install --file requirements.txt` to get all of the packages, rather than having the user run a specific command.

**Comment by stefsmeets** [comment]
Or `pip install -r requirements.txt`.

I think part of this discussion should also be to directly set up a (minimal) `pyproject.toml`. I think this should be preferred over `requirements.txt`
