### ISSUE TITLE
Observational metrics

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#113]
It would be interesting to calculate measures of transit depth and contrast ratio over time, so that we can learn about what these planets might look like at different stages of their evolution.

Calculating transit depth could be done simply by taking the height at 1 mbar and dividing this by the stellar radius. This would be only a bolometric transit depth, and assumes that tau=2/3 at the 1mbar level.

Contrast ratio could be calculated as the ratio of total TOA flux to the stellar emission, scaled to an appropriate distance.

**Comment by timlichtenberg** [comment]
Agree, only R_planet^2/R_star^2
