### ISSUE TITLE
Move documentation to markdown

### ISSUE THREAD

**Issue by stefsmeets** [FormingWorlds/PROTEUS#119]
Just had a short chat with @lsoucasse , we discussed the idea of moving the documentation to markdown with mkdocs. See also the discussion in JANUS: https://github.com/FormingWorlds/JANUS/issues/29

**Comment by nichollsh** [comment]
I agree that this would be better than the current formulation of the documentation. Is the JANUS one already online?

**Comment by lsoucasse** [comment]
> I agree that this would be better than the current formulation of the documentation. Is the JANUS one already online?

Yes, you can see it on https://fwl-janus.readthedocs.io. For now it only displays the installation instructions that were on the README. Need to complete it with usage/functionalities description.

**Comment by timlichtenberg** [comment]
Agree as well, it would be good to have a consistent format for the documentation in all modules.

**Comment by stefsmeets** [comment]
@timlichtenberg could you add me as a maintainer for PROTEUS on readthedocs?

**Comment by timlichtenberg** [comment]
Added both and Stef.
