### ISSUE TITLE
Move JANUS wrapper to JANUS repo

### ISSUE THREAD

**Issue by stefsmeets** [FormingWorlds/PROTEUS#120]
PROTEUS now handles a lot of the wrapping of JANUS, see https://github.com/FormingWorlds/PROTEUS/blob/master/utils/janus.py. 

Contextually and for better separation of concerns, the `RunJanus` class fits very will in the JANUS code. This will make it easier to maintain the code (just import `RunJanus`), and makes JANUS a bit more standalone.

**Comment by lsoucasse** [comment]
Created a symmetric issue on the Janus side:
#FormingWorlds/JANUS#47
