### ISSUE TITLE
Generic submodule handling

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#126]
We recently discussed how best to handle many submodules in a simple and transparent manner. For example, in cases where the interior can be handled by either SPIDER or Aragog. 

This can be done by having an `interior.py` file (for example) which handles generalised interior stuff, and then calls the appropriate submodule-specific functions (e.g. `RunSPIDER` in `spider.py`) as necessary. This will reduce the amount of duplicate code and therefore also make things easier to maintain.

Touches on #74 and #62

**Comment by nichollsh** [comment]
I agree. We could format the proteus package directory like so:

- src/proteus/
  - interior/
    - \_\_init__.py
    - spider.py
    - aragog.py
  - atmosphere/
    - \_\_init__.py
    - janus.py
    - agni.py
    - dummy.py

And so on

**Comment by stefsmeets** [comment]
@nichollsh I was just about to make this post, this is exactly what I had in mind as well! 😅

Eventually, all files in the `plot`, `utils`, `tools` directories and `proteus.py` should either move somewhere under `src/janus`. Or, if they are simply scripts that you expect users to edit (i.e. these do not provide any library functions), we can move them under `./scripts` or `./examples`.

**Comment by timlichtenberg** [comment]
The structure above sounds reasonable to me. What do we do with "interface" modules, such as the future atmodeller module, and ZEPHYRUS? Could all go in one of the two, but then MORS becomes a bit weirdly placed.

**Comment by lsoucasse** [comment]
I think we just follow the main proteus script, each tick being a subdirectory:
- stellar flux (Mors)
- escape (Zephyrus, dummy, others...)
- atmosphere(agni, janus, dummy..)
- outgassing (atmodeller, others...)
- interior (Spider, aragog, ...)

**Comment by timlichtenberg** [comment]
Ok, makes sense to me. Let's call "stellar flux" "star" for simplicity?

**Comment by lsoucasse** [comment]
Just to not duplicate the work, I have started this in the atmos_wrapper branch.
