### ISSUE TITLE
Remove Janus, Mors and Socrates submodules

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/PROTEUS#135]
Now that the release workflow is set up for Janus and Mors, we can delete these submodules and add them to the dependency list. We need however to be version-specific in the pyproject.toml to point to the correct version, especially at this moment where things are quite changing.

For Socrates, both Janus and Agni provides download/install function. We can thus delete the submodule but need to harmonize access from Janus/Agni and solve #134 first.

**Comment by timlichtenberg** [comment]
Before we do this: how does this change the developer installation path? Can you still have all submodules within the PROTEUS directory without cloning everything manually?

**Comment by lsoucasse** [comment]
For a developer install, you can still clone the Mors or Janus repo anywhere in your computer (it does not have to be within the PROTEUS directory). Then you run `pip install -e .` in Mors or Janus and this will install your "own" local version.

**Comment by stefsmeets** [comment]
`pyproject.toml` specifies the requirements on janus and mors, so if these are satisfied by a local installation like @lsoucasse suggested, then this will also work. If they are not found, `pip install .` in the proteus directory will pull them from pypi.

**Comment by nichollsh** [comment]
How will SOCRATES be handled in this case, since it won't be picked up by the pip command?
