### ISSUE TITLE
Refactor `start_proteus.py`

### ISSUE THREAD

**Issue by stefsmeets** [FormingWorlds/PROTEUS#141]
As discussed at yesterdays meeting, I'm opening this issue to track the progress with refactoring `start_proteus.py`.

The goal is to move all the logic etc into the library so that it can be re-used elsewhere. The goal is to have 3 entry points:

1. `start_proteus.py`, this will work in the same way as before. It will just be a lot smaller. This can be used to specify config variables, paths etc, but the main code will be elsewhere.
2. `proteus start`, this will be a CLI tool that starts proteus. The advantage is that it can be started from anywhere and does not require the user to git clone the repo. This will be more relevant as we move away from the submodules.
3. Python api, e.g. in a jupyter notebook. This is somewhat similar to 1. This will enable more exploratory use of the code, e.g. by importing the proteus class into your code: 

```python
from proteus import Proteus

handler = Proteus(cfg='input/default.cfg')
handler.start()
```

**Comment by nichollsh** [comment]
In this sense, will all variables for a given run then be contained within the PROTEUS class and objects within it? I can see that this might also make multiprocessing significantly simpler.
