### ISSUE TITLE
About plotting functions in `src/proteus/plot/ `

### ISSUE THREAD

**Issue by stefsmeets** [FormingWorlds/PROTEUS#143]
Hi all, I was wondering about the plot functions in `src/proteus/plot/cpl_*.py`. I know that some of these get run in the Proteus main loop to produce the plots.

But all of these also have entry points (`if name == __main__`), which indicates to me that they are also supposed to be run directly. Could you tell me how this is this meant to work?

I was thinking we could fold those into the proteus CLI to make these funcions more accessible.

e.g.

```
proteus plot interior --config init_coupler.toml 
# or
proteus plot sflux --config init_coupler.toml 
```

And at the same time, by structuring this a bit more, we could expose it via a python api:

```python
from proteus import Proteus

handler = Proteus(config_path='init_coupler.toml')
handler.plot('interior', **kwargs)
# alternative
handler.plot_interior(**kwargs)
```

Let me know what you think.

**Comment by nichollsh** [comment]
I have been using the `__main__` entry points as a way of plotting graphs from model outputs directly from the command line. This is useful when debugging the graphing routines, and also for when certain graphs are not automatically generated (e.g. when plotting frequency is set to zero).

Interacting with this through a cohesive CLI makes sense to me, although I can imagine this might create additional overhead?

**Comment by stefsmeets** [comment]
The overhead from the cli bit is minimal. The code will spend the most time reading/processing data and preparing the plots.

I'm also hoping that this will help make the plots more testable.

**Comment by timlichtenberg** [comment]
I just want to point out here quickly that it will be important that one can use and execute these plotting scripts standalone, without any overhead or additional packages to be installed, as is the case currently. For BSc/MSc/PhD students they serve as example of how to construct personalised plotting routines. So the idea is that the students can copy these scripts, and then "make them their own". Please ensure this capability stays.

**Comment by stefsmeets** [comment]
You mean, as in `python src/proteus/plot/cpl_elements.py`?

The additional packages being anything that already proteus depends on, correct?

**Comment by stefsmeets** [comment]
You can have a look at [plots](https://github.com/FormingWorlds/PROTEUS/tree/plots) with what I had in mind:

```console
# list available plots
$ proteus plot --list
Available plots:
interior global
```

```console
# plot interior, global
$ proteus plot interior global --config init_coupler.toml
Plotting: global
Plotting: interior
```

I have only done interior and global for now, but the rest is not so difficult to do. I will make a PR later this week.

**Comment by stefsmeets** [comment]
With the PR we get direct api access to the plots. Ideas for follow-up:
- with the dispatch table, plots become configurable in the toml `plots = ['interior', 'atmosphere']`
- Plots can be generated in a single round in the proteus core loop
- If we factor out the `plt.savefig`, plots become testable
- Users specify paths to their own plotting scripts, either on the cli or config, proteus can use these as well for custom plots: `proteus plot --script my_plot.py`
