### ISSUE TITLE
Emission spectrum calculation

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#154]
It would be a useful metric to have an easy way to generate emission spectra. This could be done on the fly or post-processed with a high resolution spectral file, or both.

It should be simple enough to do this, now that JANUS and AGNI are outputting NetCDF files with the same variables and formatting.

**Comment by timlichtenberg** [comment]
I think this plot would be so useful, that it is worth being generated on the fly with low-resolution data, and – if necessary – then with higher-resolution spectral files optionally afterwards. Perhaps with a flag that determines the resolution of the spectral generation?
