### ISSUE TITLE
Rename master branches to "main"

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#157]
As per https://github.com/orgs/FormingWorlds/discussions/156.

The master branches in each of the following repositories should be renamed to "main".
- [x] PROTEUS
- [x] JANUS
- [x] MORS
- [x] ZEPHYRUS

**Comment by nichollsh** [comment]
And just FYI: I do not have permissions to do this, so someone else will have to assign themselves to this role.

@timlichtenberg ?

**Comment by timlichtenberg** [comment]
Do you want the permissions...? :>

**Comment by lsoucasse** [comment]
I can do it for Mors as I got Admin permission at the moment.

**Comment by timlichtenberg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github issue 1](https://trello.com/c/bx2LN2iI/3-github-issue-1)

**Comment by lsoucasse** [comment]
Done for Mors.

**Comment by nichollsh** [comment]
> Do you want the permissions...? :>
@timlichtenberg yes please

**Comment by nichollsh** [comment]
Turns out I have permissions for JANUS, so I have done that too.

**Comment by timlichtenberg** [comment]
@FormingWorlds/proteus-admins I now created another team that gives admin access to the main PROTEUS repos on here. I am not sure this is the best idea, but let's do this for now while so much of the code reorganisation is going on.

**Comment by nichollsh** [comment]
FYI: The commands to run on your local clones for each of the repositories are as follows:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
This will update the remote branch to `main`. For new installations this will automatically be the case.

**Comment by EmmaPostolec** [comment]
Just done it on the cluster and my local computer thanks a lot for the instructions @nichollsh ! :)

**Comment by nichollsh** [comment]
This has been done for all repos. Closing as completed.
