### ISSUE TITLE
SOCRATES: automatically use atmospheric bulk properties

### ISSUE THREAD

**Issue by mark-hammond** [FormingWorlds/PROTEUS#16]
At the moment, we have to set atmospheric properties such as gravity through the rad_ccf file in Socrates. As these can change with time in the coupled model, we should either load these through rad_ccf (possibly like the method in Cl_run_cdf) or edit the model so that they're in a namelist.

**Comment by timlichtenberg** [comment]
Initial conditions homogenised throughout PROTEUS.
