### ISSUE TITLE
Editable dependencies broken?

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#160]
Now that JANUS and MORS have been removed as submodules of PROTEUS, they are automatically installed as dependencies from pypi. This is useful for non-developers.

However, a developer will want an editable install which makes a symbolic link from the environment directory to wherever the modules have been cloned to. 

Installing JANUS (or MORS) with `pip install -e .` initially works as expected. However, if you run the `pip install` step for PROTEUS' `pyproject.toml`, it will overwrite the JANUS and MORS installations with ones from PyPI. This makes them no longer editable.

Additionally, it is not trivial to then reinstall the editable versions. Simply re-running `pip install -e .` in the MORS and JANUS folders does not replace the PyPI versions. A workaround is to manually delete MORS and JANUS from the `site-packages` directory, and then run the editable install again.

Overall, this is pretty clunky. @lsoucasse and @stefsmeets do you see the same behaviour?

**Comment by nichollsh** [comment]
Potentially something like `pip install --upgrade --force-reinstall --no-deps -e .` is required instead.

**Comment by lsoucasse** [comment]
> Additionally, it is not trivial to then reinstall the editable versions. Simply re-running `pip install -e .` in the MORS and JANUS folders does not replace the PyPI versions. A workaround is to manually delete MORS and JANUS from the `site-packages` directory, and then run the editable install again.
>

When I run this on my computer it uninstalls whatever version installed and replace it with the editable version.

**Comment by nichollsh** [comment]
Okay, interesting. That's the ideal behaviour. I will try this in a new environment then and see what happens.

**Comment by lsoucasse** [comment]
> Okay, interesting. That's the ideal behaviour. I will try this in a new environment then and see what happens.

And when I run pip install in root Proteus in does not try to reinstall Janus and keep the editable version (also this will not work with different version numbers...).

Maybe some hidden pip install configuration creates different behaviours?

**Comment by lsoucasse** [comment]
You can try replacing == by >= in your pyproject.toml see if it relaxes the constraint.

**Comment by nichollsh** [comment]
I think I understand what is happening now. If you install JANUS and MORS **first** then PROTEUS does not overwrite it. However, if you run `pip install` for PROTEUS **first** then the `pip install` steps for JANUS and MORS are skipped because the requirements are already satisfied during the PROTEUS install step.

Therefore, it is important that developers install JANUS and MORS before they install PROTEUS. We should mention this in the documentation.

The `--force` flags mentioned above don't seem to replace the PyPI version if you try to create an editable install. Therefore, if a developer forgets to install JANUS and MORS **before** running the PROTEUS installation step, they will need to either remove the package manually or make a new environment.

**Comment by nichollsh** [comment]
I think that this is fine behaviour, as long as the documentation is clear about the order in which things are done. There should be an optional developer step in the instructions for installing MORS and JANUS if so required.

**Comment by timlichtenberg** [comment]
I think that it is quite clunky tbh and should be avoided. It should not matter in which order something is downloaded and the switch between developer and user installation should be possible retroactively. Is there something that can be done about this @lsoucasse and @stefsmeets?

**Comment by nichollsh** [comment]
This has been closed but I agree that it's still a bit clunky, as @timlichtenberg says. Maybe this needs a new issue with the perspective an 'enhancement' rather than a 'bugfix'.
