### ISSUE TITLE
Long term archive of PROTEUS source

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/PROTEUS#166]
It would be nice to setup an archiving process of old versions of PROTEUS, independently of Github, so we can make sure we never loose history, especially for submodules we have less control on. This could be done on a yearly basis, starting from early 2024 (i.e. before starting the eScience project).

**Comment by nichollsh** [comment]
Definitely a good idea. It is possible to clone the entire history of a Git repository with the following method: https://stackoverflow.com/a/54040382

We could potentially upload it to OSF using their API.

**Comment by lsoucasse** [comment]
The `git bundle` command sounds attractive. But we have to separately bundle each of the submodules.

**Comment by lsoucasse** [comment]
I have uploaded a bundle of PROTEUS v24.04.04 with all associated submodules [here](https://osf.io/8w9tm/). Could you try it @nichollsh and @timlichtenberg ? Once you download the folder, you can just run the script `restore-proteus-v24.04.04.sh`and it will clone the PROTEUS repo with its submodules.

**Comment by lsoucasse** [comment]
I realize I could also add a bundle of the AGNI repository. But it is hard for me to choose the correct compatible version except from the date. Overall, I think it is something missing as we have no information in the doc which (minimal) AGNI version to use. Maybe something to fix @nichollsh ?

**Comment by lsoucasse** [comment]
Just added a bundle of agni to the archive (version of March 28, commit tag c5ab86c).

**Comment by timlichtenberg** [comment]
Works like a charm! :-) Like we discussed today this archive should essentially be only for the past from now to be able to recreate the git history for when we start deleting larger items from the history.

**Comment by lsoucasse** [comment]
Thanks for your feedback. I am closing this issue now. We might set up later an automatic archiving process, on a yearly basis.
