### ISSUE TITLE
Transfer `surface_gases.py` to the new CALLIOPE package

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#171]
There has (and continues to be) significant scientific interest in the mass-balance equilibrium functionalities of `surface_gases.py`. It would therefore make sense to turn this into a standalone package so that it can be interacted-with more easily without installing all of PROTEUS.

Since this formulation will be mostly superseded by Atmodeller soon, any changes should probably avoid significant development.

**Comment by nichollsh** [comment]
@timlichtenberg does this sound okay to you?

**Comment by timlichtenberg** [comment]
(Repo name optimally female… :>)

**Comment by nichollsh** [comment]
I think it would make sense to keep CETO separate from the new module, since it's presumably something we won't be developing?

**Comment by nichollsh** [comment]
Let's keep it separate for now, and discuss merging them in the future, then. Moving surface_gases seems to be the main thing to do anyway.
