### ISSUE TITLE
Tests: MacOS runner

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#172]
It would be useful to setup the tests to run a matrix of different Linux and Python versions, in order to catch potential issues which arise only for certain platforms.

C.f. https://github.com/FormingWorlds/MORS/issues/22

**Comment by nichollsh** [comment]
At the same time, we should use V4 of the Cache action, since the current V3 has some significant slowness when doing the post-job clean up step. I have noticed that the action seems to 'hang' for several minutes after the cache step has completed, which has also been noted here: https://github.com/actions/toolkit/issues/1578#issuecomment-2253355054.

**Comment by nichollsh** [comment]
The above issue with Cache V4 has been resolved.

Seems like the only runner images are Ubuntu, MacOS, and windows. We could add a MacOS one, but unfortunately the Linux side is limited to Ubuntu. There's no planned support for Windows, since they can just use WSL.

**Comment by stefsmeets** [comment]
What issues do you expect on a non-ubuntu linux?

**Comment by nichollsh** [comment]
I don't have any in mind specifically, but the issue that Laurent has been facing (MORS getting different values on different platforms, despite being pure Python) indicates that this is something that we should consider.
