### ISSUE TITLE
Add physical tests

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#182]
It would be useful if the model ran a few iterations (or even a full integration) as a test, to catch issues that aren't immediately obvious in a PR or don't arise when testing individual components.

This requires the following to be achieved:
- [ ] Compile PETSc action (could be cached for performance quite easily)
- [x] Install JANUS/SOCRATES action
- [ ] Install SPIDER action
- [ ] Workflow for running PROTEUS from a configuration file

**Comment by lsoucasse** [comment]
I am afraid PETSC is still the bottleneck here. @stefsmeets already tried to set up a full install workflow but did not manage because of that.

**Comment by lsoucasse** [comment]
An intermediate step would be to have a full dummy model, that is fast to run but still covering most of the code in testing. But first we need to setup a dummy interior model #184 . What do you thinK?

**Comment by nichollsh** [comment]
I think that a dummy interior model would be quite easy to construct, if we make some broad assumptions like we do for the dummy atmosphere. I'll look into this. If it makes setting up tests possible, then this seems like a valuable thing to have.

What was the problem with PETSc?

**Comment by stefsmeets** [comment]
You need to compile it from scratch in the CI for the sundials support that is needes for SPIDER. This takes an incredible amount of set up and takes a long time to run in the CI.

**Comment by stefsmeets** [comment]
See this comment for context https://github.com/FormingWorlds/PROTEUS/pull/149#issuecomment-2311927452

**Comment by stefsmeets** [comment]
You could supply a custom docker image with the dev environment, which may be an option here.

**Comment by nichollsh** [comment]
Ah yes, I remember you describing this issue now. If we are going to be replacing SPIDER with aragog, and soon will have a dummy interior model, then it seems that spending time on getting SUNDIALS (etc) working is probably not for the best.

**Comment by nichollsh** [comment]
Closing this in favour of #186
