### ISSUE TITLE
Setup a dummy interior model

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/PROTEUS#184]
I think a dummy interior model would be helpful for testing and also for skipping the PETSC/SPIDER step. Something like the dummy atmosphere model would be valuable. Any idea @timlichtenberg, @planetmariana @nichollsh ?

**Comment by nichollsh** [comment]
I guess a very simple model would just assume that the interior has a constant heat capacity and density, and then simply cools according to the atmospheric energy transport (or blackbody emission if also using dummy atmosphere).

Adding this into the code would also make way for setting up Aragog, as we'd have to generalise the interior interface.

**Comment by nichollsh** [comment]
https://github.com/FormingWorlds/PROTEUS/tree/dummy_int
