### ISSUE TITLE
Tests: PROTEUS simulation with dummy submodules

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#186]
There are currently no tests which run the PROTEUS code - specifically, the main loop.
With dummy interior and atmosphere models implemented, this should now be significantly easier to do. We can run the PROTEUS loop without compiling SOCRATES, PETSc, or SPIDER.

Depends on: 
- #184
- #73

**Comment by nichollsh** [comment]
Test suggestions:
- Escape time
- Solidification time
- Rad eqm time 
- Atmospheric composition

**Comment by stefsmeets** [comment]
Use input/dummy.toml for the tests

**Comment by timlichtenberg** [comment]
Check for:
- Surface temperature
- Melt fraction
- Atmosphere has escaped
- Atmosphere composition at start
- Time
- Heat flux at specific time steps

**Comment by lsoucasse** [comment]
I think we can actually check the whole output csv table, might be easier to see where things diverge in time.
