### ISSUE TITLE
Dummy tidal heating calculation

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#190]
For some of the planets of interest, tidal heating could be significant. [This paper](https://iopscience.iop.org/article/10.3847/1538-4357/ab0c21/pdf) calculates tidal heating on TRAPPIST-1 b to be up to several 100 W/m^2. For the planet L 98-59 d it could be up to 1000 W/m^2. This could be the difference between a solid surface and a deep magma ocean. The methods in the paper above are too complicated for a dummy tidal model.

A first step would be to implement a dummy tidal heating module. Ideally, this would be handled by Aragog (or SPIDER). However, a very simple approximation would be to use a fixed value of energy dissipation [W m-2 kg-1], which is then scaled by the mass of the mantle [kg], and then subtract this from the heat flux escaping the interior. This would essentially represent a global tidal heat dissipation that acts to slow down (or prevent) solidification of the planet.

We should explore better models for this in the future. Potentially this could be handled by Aragog directly?

**Comment by nichollsh** [comment]
An alternative (and a lot more physical) approach to this would be to use the formulation outlined by Driscoll & Barnes (2015). This gives an equation for the tidal heat dissipation (Eq 2) based on planet and orbital parameters. It requires making some assumptions about the material properties of the mantle - but that's okay for now.

**Comment by timlichtenberg** [comment]
This seems like a good model to implement. There will be another model of Farhat+ coming out soon, which also includes a model of fluid tides. Let's add both in the to do list.

**Comment by nichollsh** [comment]
Sounds good! It would be interesting to compare the various models. In this paper, they seem to show tidal heating differences ~10 orders of magnitude, depending on the material properties you assume.
