### ISSUE TITLE
Remove SPIDER/PETSc submodules

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#196]
We aim to replace SPIDER with Aragog as the main interior module. This means that we should remove SPIDER (and its dependency PETSc) as Git submodules, and instead source them by other means.

One option is to use a simple script (c.f. `get_socrates.sh`) so that the user (or a workflow) can download them only as required.

@stefsmeets @lsoucasse do you have any other suggestions for how to handle this? Or does using a script sound okay?

**Comment by lsoucasse** [comment]
I guess it is fine to use a similar script. We might think of having a generic tool that can be used for any optional module like:
`proteus get-submodule spider`
`proteus get-submodule agni`
...

**Comment by nichollsh** [comment]
That sounds like a good idea. We could even extend this to downloading data.
`proteus get data albedos`
`proteus get module agni`
