### ISSUE TITLE
Update documentation for new config file

### ISSUE THREAD

**Issue by stefsmeets** [FormingWorlds/PROTEUS#201]
The [documentation](https://fwl-proteus.readthedocs.io/en/latest/usage/) should be updated to reflect the config file after #189 

It would be really nice if we can use the code to autogenerate the table, i.e. by setting adding the docstrings in the data and then using [mkdocstrings](https://mkdocstrings.github.io/)

**Comment by nichollsh** [comment]
It's important that we update the documentation sooner rather than later, as with the new config format the documentation is mostly useless. We can update it statically for now, and revisit the mkdocstrings afterwards.

**Comment by stefsmeets** [comment]
Yeah, we should add docstrings to every class. It's a bit of busy work, but I don't think it will be so bad. Perhaps we can work together on this. I will set up the boilerplate for mkdocstrings and set up a template for the docs.

**Comment by nichollsh** [comment]
Sounds good! I am happy to fill in the documentation strings themselves, if you can set up some kind of mechanism for generating the documentation from the code.

**Comment by stefsmeets** [comment]
I made a little start in #217, I think I will have it ready later today.
