### ISSUE TITLE
Crash with undefined escape model

### ISSUE THREAD

**Issue by stefsmeets** [FormingWorlds/PROTEUS#208]
If the escape model is not defined (`config["escape_model"] == 0`), `RunEscape` crashes because `solvevol_target` is undefined. What is the expected result here?

See this function:
https://github.com/FormingWorlds/PROTEUS/blob/181d4ceb790eba15d69daaa229b73857a3738d1b/src/proteus/escape/wrapper.py#L18-L61

**Comment by lsoucasse** [comment]
Actually, RunEscape must not be called if not dummy or zephyrus.

I would remove the if statement l.53 and put a statement like this in `proteus.py`
`if config["escape_model"]:`
`    RunEscape(parameters...)`

**Comment by stefsmeets** [comment]
That will only bring the undefined variable problem to the main loop of proteus as far as I can see, which expects solvevol_target in several places.

**Comment by nichollsh** [comment]
Closed by https://github.com/FormingWorlds/PROTEUS/pull/211
