### ISSUE TITLE
Distinguish between M_planet and M_interior

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#213]
Throughout the code we currently refer to the variable `M_planet`. However, in some cases this is used as the total planet mass, and in other cases as the mass of the interior (i.e. everything enclosed by the atmosphere-mantle interface).

We should use two variables to describe this: `M_planet` and `M_int`, where `M_planet = M_int + M_atm`, where `M_int` is the mass of the interior and `M_atm` is the mass of the atmosphere.

This is connected to #212, #50, #62, #82.

**Comment by timlichtenberg** [comment]
Good point, and while doing this, we may want to separate it from M_core as well.

**Comment by nichollsh** [comment]
Yeah that makes sense too. I'll make a PR for this once the current one is merged.

**Comment by nichollsh** [comment]
We will need to think about how to handle volatile mass partitioning. Should the mass of the interior decrease with outgassing? Do we provide SPIDER/ARAGOG with the dry or wet mantle mass? Or do we assume that volatile do not contribute to `M_int`? We could leave this for a next step.
