### ISSUE TITLE
Propagate varied gravity to AEOLUS

### ISSUE THREAD

**Issue by timlichtenberg** [FormingWorlds/PROTEUS#24]
Currently gravity acceleration is not propagated to SOCRATES as input parameter; needs adaption of AEOLUS and testing.

**Comment by nichollsh** [comment]
According to Nathan Mayne, the regular version of SOCRATES does not have a nice way to handle this - in the UM adaption of SOCRATES they've changed how planetary parameters are passed around. We'd need to implement surface gravity as an input parameter ourselves. I'm checking with some other people to see if they've tried this before.

The alternative is to simply change the the value of `grav_acc` in the code and recompile SOCRATES every time. This isn't ideal but it something to consider if other options are unfeasible.

**Comment by nichollsh** [comment]
According to James Manners, an upcoming update to SOCRATES will allow planetary parameters to be passed in via a namelist file. [This change](https://code.metoffice.gov.uk/trac/socrates/changeset/1250/main/branches/dev/jamesmanners/um13.0_planets) will be merged into the main branch of SOCRATES "fairly soon".

It's addressed in [this ticket](https://code.metoffice.gov.uk/trac/socrates/ticket/103) which is the same one which will simplify the spectral file tools. This change also relates to [this issue in the AEOLUS repository](https://github.com/FormingWorlds/AEOLUS/issues/20).

There's an example namelist file for Mars [here](https://code.metoffice.gov.uk/trac/socrates/browser/main/branches/dev/jamesmanners/um13.0_planets/examples/mars/planet.nml?rev=1250).

**Comment by timlichtenberg** [comment]
Ok, seems like recompiling the code will be way to go for the time being. Is the recently updated SOCRATES version then truly the best bet?
