### ISSUE TITLE
Condition on Pxuv computation (only for Zephyrus escape) + check on Mors/Baraffe tracks

### ISSUE THREAD

**Issue by EmmaPostolec** [FormingWorlds/PROTEUS#258]
Add few lines in the atmos_clim wrapper to compute Pxuv only if zephyrus is activated as suggested by @lsoucasse in #227 

Quotting @lsoucasse here : 
" It would be worth adding an "if zephyrus activated" statement to the Pxuv computation, and if not fill the Pxuv entry with the surface pressure. I think it kind of goes with issue https://github.com/FormingWorlds/PROTEUS/issues/232. "

**Comment by lsoucasse** [comment]
Could you also add in this work a check that Mors/Baraffe tracks are selected when running zephyrus. It should break if not. Then it will solve #232 .

**Comment by timlichtenberg** [comment]
Why is Zephyrus incompatible with Spada tracks btw?

**Comment by lsoucasse** [comment]
> Why is Zephyrus incompatible with Spada tracks btw?

It is the other way around. Zephyrus can only work if Spada tracks (Mors) are used.

**Comment by timlichtenberg** [comment]
Ok, thanks for clarifying! This means Spada tracks should always be the default option in all config files.

**Comment by lsoucasse** [comment]
Issue closed by PR #290.
