### ISSUE TITLE
Allow resuming simulation from disk when using aragog

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#263]
It's helpful to be able to resume the simulation from the disk. This is possible with SPIDER/Dummy interior modules, but currently not with Aragog.

**Comment by lsoucasse** [comment]
Do you get an error when you try to resume or is still "just" non consistent because it does not use correct initial condition?

**Comment by nichollsh** [comment]
I don't get a particular error. I think it's just the latter, because when I attempt this the time gets reset to zero and the graphs start looking quite odd.

**Comment by lsoucasse** [comment]
OK, so we need to get back the last temperature field as well as the restarting time.
