### ISSUE TITLE
Problem with NetCDF version while using SOCRATES on Norma2

### ISSUE THREAD

**Issue by EmmaPostolec** [FormingWorlds/PROTEUS#271]
Hi all, 

Recently, I ran into a problem trying to run PROTEUS on the Kapteyn cluster (Norma2). @planetmariana also tried running Proteus on Norma2 and encountered the exact same error. I got a NetCDF error that I never encountered while running PROTEUS on my local computer. @nichollsh found that the problem was that SOCRATES was using the wrong version of NetCDF. SOCRATES was using the NetCDF version installed by Python in my PROTEUS environment instead of the NetCDF version installed on the cluster system.  
To debug, I deactivated all conda environments, then deleted the `socrates/` directory and ran the ```./tools/get_socrates.sh``` command to get SOCRATES again, but **outside any conda environment.** Then, I ran the ```cat socrates/set_rad_env``` command to make sure SOCRATES was pointing to the correct NetCDF version. Finally, I ran a PROTEUS simulation using the `default.toml` config file, and it’s working now. 

@nichollsh and I thought about opening a new issue to discuss updating the documentation on the installation webpage of PROTEUS. This would inform users to install SOCRATES outside of a conda environment to avoid problems like this in the future. Let us know what you think about this. @timlichtenberg

**Comment by timlichtenberg** [comment]
Awesome! :) Yes, please update the documentation files accordingly. Before doing that, a question: does this work the same way on your local computer, or is this only a specific problem for Norma1/2? 

If it is the latter, instead of updating the standard installation instructions at https://fwl-proteus.readthedocs.io/en/latest/installation/, you may want to add a new section to it that specifically deals with tips&tricks for the Kapteyn clusters.

**Comment by EmmaPostolec** [comment]
This issue is specific to Norma1/2. On my computer, it always pointed to the correct NetCDF version directly.

Sure, that makes sense! Thanks! :)

**Comment by timlichtenberg** [comment]
Ok, then I suggest to add a new section somewhere a bit further down (and a note somewhere in the text pointing there) and start a list with things to consider. I believe you created a Google Doc file already that lists these issues. It may be worth including the link to that to be able to quickly update this section; but all the most important tips/tricks/troubleshoots should be listed/mentioned in the Documentation installation instructions.
