### ISSUE TITLE
GitHub workflow sometimes fails on MacOS

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#280]
Sometimes the MacOS test workflow fails on the step where it installs the brew dependencies. This is the first step of the workflow, so it's not directly related to core PROTEUS code. See example here: https://github.com/FormingWorlds/PROTEUS/actions/runs/11953651244/job/33321985018

**To Reproduce**
Run the test workflow with a MacOS runner.

**Expected behavior**
For brew to execute without errors.

**Additional context**
These seem to be the same problem: https://github.com/Homebrew/brew/issues/17224, https://github.com/apache/arrow/pull/44798

**Comment by nichollsh** [comment]
@stefsmeets do you have any suggestions for how to fix this?

**Comment by nichollsh** [comment]
I just noticed that the second issue mentioned above (https://github.com/apache/arrow/pull/44798) is only 4 hours old, so maybe this will be fixed further up in the supply chain.

**Comment by stefsmeets** [comment]
Could we mimick the apache changes:

https://github.com/raulcd/arrow/blob/e45627d759bb499ee58e72de42a7ea7319cc2204/.github/workflows/python.yml#L192-L195

Seems like pkgconf is already installed and brew fails to recognize this and somehow does not have rights to overwrite it.
