### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by timlichtenberg** [FormingWorlds/PROTEUS#36]
- Create basic description of code structure
- Describe main features and current functionality
- Update incrementally while adding new features

**Comment by lsoucasse** [comment]
Is this issue still valid @timlichtenberg? Or should we update it to include the points we discussed recently (having specific install instructions for Kapteyn cluster / pointing to documentation of individuals submodules).

**Comment by nichollsh** [comment]
This is something which should be continually performed as issues come and go. Closing this issue as there are no specific targets associated with it, and the documentation is now in a much better state compared to when this issue was first created.
