### ISSUE TITLE
Integrate ZEPHYRUS escape module

### ISSUE THREAD

**Issue by timlichtenberg** [FormingWorlds/PROTEUS#46]
- [x] Add escape module ZEPHYRUS with minimum escape functionality to test PROTEUS integration
- [x] Link with PyPI Zephyrus package once ready FormingWorlds/ZEPHYRUS#3
- [ ] #93

**Comment by nichollsh** [comment]
Does ZEPHYRUS have any online sources, or is it a new code that's not yet published?

**Comment by timlichtenberg** [comment]
@richard-chatterjee is currently working on a first basic version, which will be made public soon. :)

**Comment by timlichtenberg** [comment]
Zephyrus module meeting on 2 July 2024 at 10.00 CEST.

**Comment by timlichtenberg** [comment]
This is now next up.

**Comment by timlichtenberg** [comment]
In progress: next up for this is to double check that the calculated escape fluxes in PROTEUS match those in standalone ZEPHYRUS. @EmmaPostolec

**Comment by lsoucasse** [comment]
Zephyrus is now integrated. Closing this issue as volatile fractionation is an issue on its own.
