### ISSUE TITLE
Conductive skin parameterisation between atmosphere and melt

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#49]
To satisfy energy balance through the surface, we need some kind of treatment. The simplest case is simply that T_surf in the atmosphere equals T_surf at the top of the MO, but this isn't realistic.

Instead, we can assume a conductive skin of thickness d and conductivity k. Then, the atmosphere has to carry a flux that is equal to whatever the skin can conduct (global energy balance). The model will need to solve for the T_surf in the atmosphere that satisfies this, which will be less than that of the MO below.

This can be done using a root-finding method.

**Comment by timlichtenberg** [comment]
This is done, right?

**Comment by nichollsh** [comment]
Yes, this is implemented in the most recent versions of AEOLUS/AGNI and is called by PROTEUS. We can close this issue.
