### ISSUE TITLE
Multicomponent equation of state for atmosphere

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#52]
Need to investigate equations of state beyond the ideal gas equation, for multicomponent mixtures at high P,T.

e.g. https://en.wikipedia.org/wiki/Redlich%E2%80%93Kwong_equation_of_state

**Comment by djbower** [comment]
To avoid duplicating effort in this regard, I wanted to let you know that I have an ongoing project with regard to real gas EOS.  The python package I am developing will be open source and available in January 2024.  At which point, you can integrate this into PROTEUS (or use for other purposes, as you wish).

**Comment by nichollsh** [comment]
Oh that's fantastic - thanks for letting me know about this. I haven't explored this too much yet, but I am confident that it will be necessary to go beyond the ideal gas EOS for these thick atmospheres.

Looking forward to using your new project, when it's ready :)

**Comment by nichollsh** [comment]
I suggest that we close this issue, since it will be handled by atmodeller (or the atmosphere module where required). It shouldn't be a general PROTEUS issue.

@timlichtenberg ?
