### ISSUE TITLE
Plot fraction of surface molten over time

### ISSUE THREAD

**Issue by timlichtenberg** [FormingWorlds/PROTEUS#59]
- Make plot "Fraction of molten surface over time"
- Select from meltfrac array only the surface cells
- Then find the ones that have melt fraction > 0
- Then divide this number by total number of cells at the surface
- The plot this number over time for all simulations

**Comment by nichollsh** [comment]
@timlichtenberg is this issue meant to be in the PROTEUS repository?

**Comment by timlichtenberg** [comment]
Nope, thanks!
