### ISSUE TITLE
Introduce support for aragog interior model

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#62]
The C-based version of SPIDER is being deprecated. There is a new version written in Python being developed (https://github.com/ExPlanetology/aragog), which uses SciPy rather than PETSc and thereby simplifies things significantly.

It will therefore be necessary to implement [pySPIDER](https://github.com/ExPlanetology/aragog) within PROTEUS. Implementation of Dan's new atmosphere/outgassing/EOS code will probably also be necessary.

**Comment by nichollsh** [comment]
Once this has been done we can probably think about re-working the installation method for the framework. At the moment it's very clunky and will make it hard for others to reproduce our results.

Also, this issue makes Issue #43 redundant.

**Comment by timlichtenberg** [comment]
https://github.com/ExPlanetology/aragog/issues/6
https://github.com/ExPlanetology/aragog/issues/7

These two issues are relevant for this. In particular https://github.com/ExPlanetology/aragog/issues/6 needs to be resolved to enable physically meaningful simulations with aragog.

**Comment by timlichtenberg** [comment]
We plan to organise a Zoom meeting with @djbower, myself, @planetmariana, and @planetmariana in ~late Aug/early Sep to start this item.

**Comment by nichollsh** [comment]
Issue #126 should probably be addressed first.

**Comment by lsoucasse** [comment]
Hi @planetmariana @timlichtenberg ,

I have setup a first draft of the aragog interface in this [branch](https://github.com/FormingWorlds/PROTEUS/tree/aragog-constant), see `src/proteus/interior/aragog.py`. For now it runs from some default options and the output solution is not put.

Now I need your help to:
- correctly fill the initial input parameter from proteus options in `SetupAragogSolver`
- update the boundary conditions in `UpdateAragogSolver`
- collect the output from solver solution in `GetAragogOutput`

Maybe you can have a look by next Monday and we go though all this together during our meeting.

**Comment by stefsmeets** [comment]
I'd highly recommend setting this up as a class instead of a global:

```python
class AragogSolver:
    def setup(...):
    def update(...):
    def run(...):
    def get_output(...):
```

Shouldn't take more than 5 min to implement this. This will make it much easier to refactor/update the code at a later stage, and also keep the code decoupled for parallelization.

**Comment by lsoucasse** [comment]
Hi @planetmariana and @timlichtenberg ,

I have setup two inputs for testing aragog:
- dummy_aragog.toml which takes the dummy example but replaces the dummy interior by aragog
- default_aragog.toml which takes the default example but replaces spider by aragog

The first one runs till the end (atmospheric escape) but cooling seems fast. The second crashes after 5 iteration with a magma temperature of -8000K. Any thoughts to debug this ?

To run these examples you need to work with the `aragog-constant` proteus branch and with the `add-output` aragog branch.

**Comment by nichollsh** [comment]
I have never actually tried SPIDER+dummy atmosphere, which roughly corresponds to the first case you describe. However, with the dummy atmosphere we should expect quite fast cooling since it's effectively just a bare rock. Do the plots show the same behaviour as with the other models? 

I'll give this a go if I have time today.

**Comment by nichollsh** [comment]
And on the second one: I would suggest investigating where the -8000 K comes from. Is it from the atmosphere or the interior? Does it happen with SPIDER/dummy interior too?

**Comment by nichollsh** [comment]
I have been able to run the `dummy_aragog.toml` example (although it actually had `interior.module="dummy"`, but I changed this locally) and can see that yes it does cool very fast. Strange.

**Comment by nichollsh** [comment]
Also I guess this is something that needs to be looked at later: but Aragog does *not* like it when you try to resume the PROTEUS simulation from a previous point. I think it's getting semi-reset to the beginning?

**Comment by nichollsh** [comment]
![plot_global_log](https://github.com/user-attachments/assets/4d8d2324-e818-491e-afe9-c3d8b4ee7b89)

**Comment by lsoucasse** [comment]
> Also I guess this is something that needs to be looked at later: but Aragog does _not_ like it when you try to resume the PROTEUS simulation from the disk. I think it's getting semi-reset to the beginning?

The resume feature is not supported yet.

**Comment by timlichtenberg** [comment]
Yes, that makes sense to me.
