### ISSUE TITLE
Extend MORS sub-module

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#68]
We are currently pulling MORS from Colin's repository on GitHub as a submodule. As part of the effort to remove dependence on external GitHub repositories, I've forked this into a new repository within the FW organisation: https://github.com/FormingWorlds/MORS.

Since this now gives us the opportunity to modify and maintain the code, I also propose the following...
- Action #56 as part of this Issue by allowing MORS to automatically obtain spectra from PHOENIX.
- Move the stellar spectrum synthesis code from PROTEUS (e.g. `utils/stellar_common.py`) into MORS so that all of the star-stuff is handled within the one module.

**Comment by timlichtenberg** [comment]
How far do you think did the last commit to the main branch go with this @nichollsh?

**Comment by nichollsh** [comment]
I haven't yet attempted to do either of the bullet points listed above. MORS has been moved into a FW repository, and PROTEUS now pulls that, but the module itself is untouched.

**Comment by nichollsh** [comment]
I am actually wondering if we do not need MORS at all. We can probably use the Baraffe stellar evolution tracks to obtain Teff, log(g), and mass. This can then be used to get the appropriate spectrum from the PHOENIX database. 

If we also wanted XUV flux as scalar values, these could be easily obtained from the PHOENIX spectra.

Just an idea.

**Comment by timlichtenberg** [comment]
Renamed to clarify updated status of the MORS module.

**Comment by nichollsh** [comment]
I do not think that this PHOENIX scaling idea is the way forward. Someone already explored this and found that scaling the spectrum works well. This should then also be an issue in MORS rather than PROTEUS, since that is the module which will require modifications.

Closing this and opening a new issue in MORS.
