### ISSUE TITLE
Model output compression and storage

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#70]
It is important to be able to store, share, and analyse model outputs. At the moment, PROTEUS generates an output folder for each simulation and places most of the files within a `data/` subfolder. This is fine, but it does not make the outputs easy to share.

We should consider a friendlier method for sharing the outputs of the model, particularly if it includes compressing the data. Simply compressing the `data/` folder into a Zip file for the current earth_demo case reduces its size by a factor of 3.3x, which is important to consider when running many models across a grid.

The ideal case would be to synthesise the model output into a single file, including everything from SPIDER, SOCRATES, etc. If done properly, this is highly portable and much faster than reading many separate files. E.g. using Xarray it is possible to read only part of a file from the disk.

Potentially connected to Issue #71.

**Comment by nichollsh** [comment]
Running a large-ish grid of models indicates that this is going to be an issue going forward. I have a grid with 1029 points (7*7*7*3) running, which will take about 92 hours to complete. However, the total final size is estimated to be at least 516 GB. This is unreasonably large if we want to analyse the results.

I am sure there's a way to store the output in a format which is smaller on disk and easier to read.

**Comment by timlichtenberg** [comment]
This seems like good discussion with @lsoucasse and @stefsmeets in the next few weeks.

**Comment by timlichtenberg** [comment]
Since this keeps coming up, wha about we simply move every output everywhere to HDF5 file format (https://docs.h5py.org/en/stable/index.html)?

**Comment by timlichtenberg** [comment]
Ok, makes sense to me. If @lsoucasse is fine with, let's aim for unifying all data output to NetCDF then in the future.

**Comment by lsoucasse** [comment]
Sounds good for me.

**Comment by nichollsh** [comment]
Excellent. I think the first step towards this would be to separate input/output variables, as discussed before. Then when we've defined what exactly is an "output" (for now) we can hopefully make an easy move towards using NetCDF.

We can use Xarray to open/close the NetCDF files, potentially, or just interface directly with the netCDF4 library.

**Comment by timlichtenberg** [comment]
- [ ] Disentangle in- and outputs
- [ ] Rewrite JANUS output to netCD.
- [ ] Try to get rid of the coupler helpfile

Goal:
- Have one netCDF/json file per submodule

**Comment by nichollsh** [comment]
1. Disentangle input/output variables. Input variables not updated during runtime, and avoid passing entire dictionary to functions.
2. Organise output variables such that we avoid passing entire dictionary. Avoid redundant variable passing.
3. Format shared PROTEUS output data file consistently based only on model output variables. Pre-defined columns/variable names with consistent structure. With the aim of enabling easy restarts.
4. Reconsider configuration file format (issue #74)

**Comment by nichollsh** [comment]
Started work on point 1 of the above in this branch: https://github.com/FormingWorlds/PROTEUS/tree/detangle

**Comment by nichollsh** [comment]
@lsoucasse, @timlichtenberg do you feel that this issue is now completed? We have achieved all of the points above except point 4, which is covered by issue #74.

**Comment by lsoucasse** [comment]
I agree we can close it.
