### ISSUE TITLE
Self-consistent surface albedo values

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#72]
SOCRATES allows us to choose a value for the surface reflectivity (albedo) between 0 and 1. This is important for setting the energy budget of the atmosphere, and thus for the entire planet. Hamano+15 used a surface albedo of 0.2, but recent work has shown that this is probably too large. The exact value depends on the composition/mineralogy of the melt (particularly fO2) and its temperature.

It would be physically consistent if we updated the surface albedo value throughout the simulation according to the conditions at the surface. There is some empirical basis for this.

https://doi.org/10.3847/1538-4357/ab9cba
https://doi.org/10.1016/j.jnoncrysol.2005.09.003

**Comment by timlichtenberg** [comment]
The capability for this is now there in AGNI, isn't it? It would be good if Mark could implement some of the lab measurements, then this issue is essentially solved, right?

**Comment by nichollsh** [comment]
Yes, it's possible for AGNI to use a spectral surface albedo which is simply read-in from a CSV file.

We could have this be set by the configuration file, or maybe have PROTEUS choose the best one based on other parameters?

**Comment by timlichtenberg** [comment]
Having this set by the configuration file is the most useful option at the moment I think.

**Comment by nichollsh** [comment]
Definitely. Maybe we can close this issue then, since it's part of #74 ?
