### ISSUE TITLE
Rework configuration file

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#74]
The current configuration file format is very confusing. It's not clear which parameters are necessary, and how they relate to each other. I've tried to make this clearer in the ReadTheDocs page using a table, but that's not good enough.

Since we want to keep things as "modules", which are swappable, I propose that we use a TOML file for the cfg format with a section for each module being used.

For example...

```
# Example cfg file with some arbitrary values

[runtime]
log_output =  true
output_folder = "path/to/folder"

[planet]
mass = 10.0
radius = 2.0
surface_bc = 2

[star]
mass = 1e5
radius = 1e4
spectrum = "path/to/file"

[modules]

    [modules.interior]
    enabled    = true
    selection  = "C_SPIDER"
    melt_curve = "path/to/file"

    [modules.atmosphere]
    enabled   = true
    selection = "JANUS"
   
        [modules.atmosphere.initial]
        use_params = false 
        H2O_bar    = 30.0

    [modules.escape]
    enabled   = false

```

See more info here: https://toml.io/en/
This connects with #62, #68, #66, #56, and #71.

**Comment by nichollsh** [comment]
One thing that might also be useful: having multiple ways to specify the planetary parameters. It would be handy to be able to say `planet=Earth` or `planet=TRAPPIST1b` rather than specifying mass, radius, etc, directly.

**Comment by stefsmeets** [comment]
+1 on using toml for the config format. I think striving for a model like in the [JANUS config](https://github.com/FormingWorlds/JANUS/blob/master/src/janus/data/tests/config_instellation.toml) is a very good idea. 

1. Move from .cfg to .toml
2. Add [tables](https://toml.io/en/v1.0.0#table) for planet, star, etc
3. Add validation

I also want to move away from storing the data in a dictionary towards a more structured representation of the config with validation, probably in the form of a dataclass.

For validation then, I think we have 3 options:

1. Python dataclasses with a big `__post_init__` (most similar to what [we have now](https://github.com/FormingWorlds/PROTEUS/blob/bc6a55d5b127f40b8ad90656657485d12e032533/src/proteus/utils/coupler.py#L314)). Simple, not as powerful as attrs.
2. [`attrs`](https://www.attrs.org/en/stable/overview.html) library, sort of a middle-ground between pydantic and dataclasses. Has some [validation](https://www.attrs.org/en/stable/api.html#module-attrs.validators), but it is optional.
3. [`pydantic`](https://docs.pydantic.dev/latest/) library, very powerful tool for validation. I have good experience with it in the past.

Currently any and all validation seems done in: `/src/proteus/utils/coupler.py:ValidateInitFile` although the [documentation has way more rules](https://fwl-proteus.readthedocs.io/en/latest/usage/#configuration-file). The idea with validation is that this is done all in one go when reading the config. 

In addition, both attrs and pydantic offer inline descriptions, which could be used to single-source the documentation in the code and generate the tables on rtd.

I'm sort of keen to try attrs for this project.

**Comment by stefsmeets** [comment]
The changes from `.cfg` to `.toml` are minimal. The only thing to change is to add quotation marks to any string variables.

**Comment by timlichtenberg** [comment]
Sounds good to me in principle; my only worry is to keep it "simple", i.e., always having in mind that students of various levels need to be able to read and (optimally) add some code piece in the years to come.

**Comment by stefsmeets** [comment]
Yup, and at the same time you cannot make an omelette without breaking some eggs 😅 The goal here is to simplify existing procedures by using well established tools and standards.

**Comment by timlichtenberg** [comment]
Ok, do you think it's reasonable that you start making some headway with your preferred `attrs` library, and then we can see with some example code what this would mean in detail for the code restructuring?

**Comment by stefsmeets** [comment]
Yeah, I can have a go at it when we get to that point. First we should start by moving to toml, and then as @nichollsh suggested re-organize the config with toml tables.

**Comment by nichollsh** [comment]
I have drawn up a suggestion for how we could format all of the existing parameters into a structure which achieves the following:

- Allows us to add new modules and physics (e.g. aragog, structure models)
- Is relatively clear to a new user which options do what
- Prevents users from choosing conflicting options (I think this is really important)
- Balances the software- and physics-first perspectives on formatting
- Includes metadata for compatibility and authorship information
- Will not require significant changes to the code

The main downside to this structure is that the TOML tables are heavily nested. This means that variable names get quite long, so it's a somewhat easier to get 'lost' in the file if you're using a lightweight editor. In VScode and Geany (and probably others) this makes it easier to navigate because you can collapse the sections as required.

Example file attached (you will need to remove the .txt extension)
[new.toml.txt](https://github.com/user-attachments/files/17084401/new.toml.txt)

**Comment by stefsmeets** [comment]
That looks very good, I don't think the nesting is such an issue if it is well documented.

**Comment by timlichtenberg** [comment]
Looks very good to me! I went through the file (using Sublime Text) and made some changes and annotations. I think by default several of the parameters and switch options should be better described. I gave it a go in the instances it was obvious and made annotation in BOLD for things to change/clarify/double check. 

[new.toml_TL.txt](https://github.com/user-attachments/files/17094443/new.toml_TL.txt)

**Comment by nichollsh** [comment]
Thanks, both. I have tried to fill in the gaps that Tim has indicated and made some other minor tweaks.
[new.toml.txt](https://github.com/user-attachments/files/17094655/new.toml.txt)

**Comment by timlichtenberg** [comment]
Great! Minor final comment/addition:
```
H2O  = 30.0         # partial pressure of H2O [bar]
CO2  = 0.0          # partial pressure of CO2 [bar]
```

**Comment by nichollsh** [comment]
Stored the final template for the config file here:
https://github.com/FormingWorlds/PROTEUS/blob/3b7a3fcf878723e753a68077b4ebc501ec68ecba/input/new.toml

**Comment by stefsmeets** [comment]
Nice, I will get to work on this one. Note that the config system will be modular, so we can quite easily change it in the future.

**Comment by nichollsh** [comment]
I don't think we need a translation layer. In theory, it should be easy to convert old-style to new-style by hand if necessary. Any future work should be using the new format, and if someone is really really desperate to use an old config then they can just use an old version of PROTEUS.

**Comment by stefsmeets** [comment]
To help with the implementation, I think it is helpful to have a translation layer. Moving to a new config layout will mean a ton of changes in the code. The way I want to approach this is by replacing `proteus.config` by the new config object. By overriding `__getattr__`, we can redirect attribute lookups to the new layout, so that the code works without too many changes. I will then raise a warning and update the calling code to the new config. 

Below is the mapping I made this morning, it is not complete yet. Can I ask @timlichtenberg or @nichollsh to go through my mapping and check if it makes sense and fill in the blanks (labeled `None` or `# ??`)?

```python
mapping = {
 'star_model': ('star', 'mors', 'tracks'),
 'star_mass': ('star', 'mass'),
 'star_radius_modern': ('star', 'radius'),
 'star_temperature_modern': ('star', 'Teff'),
 'star_luminosity_modern': ('star', 'Lbol'),
 'star_age_modern': ('star', 'age_now'),
 'star_rot_pctle': ('star', 'omega'),
 'star_spectrum': ('star', 'mors', 'spec',),
 'semimajoraxis': ('orbit', 'semimajoraxis'),
 'mass': ('struct', 'mass'),
 'radius': ('struct', 'radius'),
 'zenith_angle': ('orbit', 'zenith_angle'),
 'asf_scalefactor': ('orbit', 's0_factor'),
 'albedo_s': ('atmos', 'surf_albedo'),
 'albedo_pl': (None, ),  # ??
 'eccentricity': ('orbit', 'eccentricity'),
 'P_top': ('atmos', Config.atmos.module, 'p_top'),
 'iter_max': ('params', 'stop', 'iters', 'maximum'),
 'log_level': ('params', 'out', 'logging'),
 'dir_output': ('params', 'out', 'path'),
 'time_star': (None, ), # ??
 'time_target': (None, ), # ??
 'spectral_file': (  # convert to Path: 'spectral_files/{spectral_group}/{spectral_bands}/{spectral_group}.sf'
    ('atmos', Config.atmos.module, 'spectral_group'), 
    ('atmos', Config.atmos.module, 'spectral_bands'), 
 ),
 'stellar_heating': (None, ), # ??
 'plot_iterfreq': ('params', 'out', 'plot_mod'), 
 'plot_format': ('params', 'out', 'plot_fmt'),
 'sspec_dt_update': (None, ), # ??
 'sinst_dt_update': (None, ), # ??
 'dt_maximum': ('params', 'dt', 'maximum'),
 'dt_minimum': ('params', 'dt', 'minimum'),
 'dt_method': ('params', 'dt', 'method'),
 'dt_propconst': ('params', 'dt', 'proportional', 'propconst'),
 'dt_atol': ('params', 'dt', 'adaptive', 'atol'),
 'dt_rtol': ('params', 'dt', 'adaptive', 'rtol'),
 'dt_initial': ('params', 'dt', ),
 'shallow_ocean_layer': (None, ),  # ??
 'F_atm_bc': ('atmos', 'janus', 'F_atm_bc'),
 'skin_d': ('atmos', 'surface_d'),
 'skin_k': ('asmos', 'surface_k'),
 'prevent_warming': ('atmos', 'prevent_warming'),
 'solid_stop': ('params', 'stop', 'solid', 'enabled'),
 'phi_crit': ('params', 'stop', 'solid', 'phi_crit'),
 'steady_stop': ('params', 'stop', 'steady', 'enabled'),
 'steady_flux': ('params', 'stop', 'steady', 'F_crit'),
 'steady_dprel': ('params', 'stop', 'steady', 'dprel'),
 'emit_stop': ('params', 'stop', 'radeqm', 'enabled'),
 'F_crit': ('params', 'stop', 'radeqm', 'F_crit'),
 'escape_model': ('escape', 'module'),
 'escape_stop': ('params', 'stop', 'escape', 'mass_frac'),
 'escape_dummy_rate': ('escape', 'dummy', 'rate'),
 'atmosphere_model': ('atmos', 'module'),
 'atmosphere_surf_state': ('atmos', 'surf_state'),
 'atmosphere_nlev': ('atmos', Config.atmos.module, 'num_levels'),
 'min_temperature': ('atmos', Config.atmos.module, 'tmp_minimum'),
 'max_temperature': (None, ), # ??
 'water_cloud': ('atmos', 'cloud_enabled'),
 'alpha_cloud': ('atmos', 'cloud_alpha'),
 'tropopause': ('atmos', 'janus', 'tropopause'),
 'rayleigh': ('atmos', 'rayleigh'),
 'atmosphere_chemistry': ('atmos', 'agni', 'chemistry'),
 'interior_model': ('interior', 'module'),
 'interior_nlev': ('interior', 'spider', 'num_levels'),
 'grain_size': ('interior', 'grain_size'),
 'mixing_length': ('interior', 'spider', 'mixing_length'),
 'solver_tolerance': ('interior', 'spider', 'tolerance'),
 'tsurf_poststep_change': ('interior', 'spider', 'tsurf_atol'),
 'tsurf_poststep_change_frac': ('interior', 'spider', 'tsurf_rtol'),
 'planet_coresize': ('struct', 'corefrac'),
 'ic_adiabat_entropy': ('interior', 'spider', 'ini_entropy'),
 'ic_dsdr': ('interior', 'spider', 'ini_dsdr'),
 'F_atm': ('interior', 'F_initial'),
 'fO2_shift_IW': ('outgas', 'fO2_shift_IW'),
 'solvevol_use_params': (None, ), # ??
 'Phi_global': (None, ),
 'CH_ratio': ('delivery', 'elements', 'CH_ratio'),
 'hydrogen_earth_oceans': ('delivery', 'elements', 'H_oceans'),
 'nitrogen_ppmw': ('delivery', 'elements', 'N_ppmw'),
 'sulfur_ppmw': ('delivery', 'elements', 'S_ppmw'),
 'H2O_included': ('outgas', 'calliope', 'include_H2O'),
 'H2O_initial_bar': ('delivery', 'volatiles', 'H2O'),
 'CO2_included': ('outgas', 'calliope', 'include_CO2'),
 'CO2_initial_bar': ('delivery', 'volatiles', 'CO2'),
 'N2_included': ('outgas', 'calliope', 'include_N2'),
 'N2_initial_bar': ('delivery', 'volatiles', 'N2'),
 'S2_included': ('outgas', 'calliope', 'include_S2'),
 'S2_initial_bar': ('delivery', 'volatiles', 'S2'),
 'SO2_included': ('outgas', 'calliope', 'include_SO2'),
 'SO2_initial_bar': ('delivery', 'volatiles', 'SO2'),
 'H2_included': ('outgas', 'calliope', 'include_H2'),
 'H2_initial_bar': ('delivery', 'volatiles', 'H2'),
 'CH4_included': ('outgas', 'calliope', 'include_CH4'),
 'CH4_initial_bar': ('delivery', 'volatiles', 'CH4'),
 'CO_included': ('outgas', 'calliope', 'include_CO'),
 'CO_initial_bar': ('delivery', 'volatiles', 'CO'),
}
```

**Comment by nichollsh** [comment]
I have clarified a few of the entries below. All others look okay.
* `'albedo_pl': ('atmos', Config.atmos.module, 'albedo_pl')` This parameter should probably be avoided, but it's handy to have around. I don't think the code currently passes it onto AGNI, but a future step can easily do this.
* `'time_star': ('star', 'age_ini')`
* `'time_target': ('params', 'stop', 'time', 'maximum')`
* `'stellar_heating'` This was initially used to turn the star off. I decided to drop this from the new configuration format, since there's never been a case where it has been useful. If we decide to keep it, then maybe it should be implemented by a dummy star module in the future.
* `'sspec_dt_update': ('params', 'dt', 'starspec')`
* `'sinst_dt_update': ('params', 'dt', 'starinst')`
* `'shallow_ocean_layer'` This is already handled by the option `atmos.surf_state = 'mixed_layer'`.
* `'max_temperature': ('atmos', 'tmp_maximum')` Similarly, we could probably move the `min_temperature` key directly into the `atmos` table, rather than storing it per-submodule. 
* `'solvevol_use_params'` This is no longer needed, as it's equivalent to choosing `delivery.initial = 'elements'`.
* `'Phi_global'` This key is no longer used to initialise the code, so it can be neglected.

**Comment by stefsmeets** [comment]
Oops, didn't mean to close this yet.

Thanks @nichollsh , with #189 merged and the dummy tests, I will try to see how far I get by simply swapping out the config.

**Comment by timlichtenberg** [comment]
Seems all good to me, thanks Harrison for the fast reply here!
