### ISSUE TITLE
Modularise stellar evolution stuff

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#75]
Currently the stellar evolution is partially handled by the Mors submodule, but the spectral synthesis is included directly within PROTEUS. It would follow the modular philosophy of the framework to move the spectral synthesis into its own module or into Mors directly. Similarly, Mors should be updated to use the Baraffe stellar evolution tracks, instead of the Spada ones.

**Comment by timlichtenberg** [comment]
Given that MORS is not actively develop anymore as I believe, we may want to create a do-it-all stellar module? What do you think?

**Comment by nichollsh** [comment]
I think that would be a good idea - I mentioned something similar in Issue #68. It would make for a very useful standalone code, especially if it were integrated with the PHOENIX database, such that it automatically pulls the appropriate spectrum (Issue #56).
