### ISSUE TITLE
External file storage (OSF)

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#76]
There are several sets of large files packaged within PROTEUS now:
- Stellar evolution tracks
- Spectral files (and possibly line-lists / opacity data)
- Stellar spectra
- Example results
- SPIDER lookup data

It would be best to host these somewhere centralised, where we have more control over them. We would be quite stuck if the 3rd-party sources made these no longer available.

This is connected to Issues #56, #56, #75, #71.

**Comment by nichollsh** [comment]
@timlichtenberg would it be possible to host the data files (spectral files, stellar evolution tracks, etc.) via the FormingWorlds website? Not with a fancy frontend or anything, but only so that the files can be downloaded easily from somewhere centralised. Just an idea.

**Comment by timlichtenberg** [comment]
Absolutely, what I would suggest though is to host on zenodo.org or osf.io, but then of course I can add a link to the FormingWorlds website to this data.

**Comment by timlichtenberg** [comment]
I created an OSF repository for that purpose and gave you read+write access: https://osf.io/8dumn/. Currently I am linking a few data repos. Let me know what else is necessary.

**Comment by timlichtenberg** [comment]
I now added components for each of the above-outlined categories to https://osf.io/8dumn/:
<img width="597" alt="Screenshot 2024-05-09 at 12 45 35" src="https://github.com/FormingWorlds/PROTEUS/assets/8751016/59d538f6-aa7f-4256-8ed2-d064b394926a">

My suggestion would be that we then replace the current Google Drive storage with these "components" within OSF. I think the storage there should be sufficient. If for some parts it is not, we can add an "Add-on" like figshare or zenodo, where we can store more data. What do you think?

**Comment by nichollsh** [comment]
I think this makes sense. The storage limit is apparently 9 GB per component, so splitting it up like this should allow for sufficient space.

There's also a python library for downloading from OSF: https://github.com/osfclient/osfclient

**Comment by lsoucasse** [comment]
This issue needs to be declined per submodule:

- [ ] SOCRATES (through Janus and Agni): spectral files
- [ ] MORS : evolution tracks
- [ ] ...

**Comment by nichollsh** [comment]
We are able to do this even without the OSF Python library. The OSF API can be accessed quite easily with `curl`.

For example, the Baraffe tracks are file ID "kzay8". We can get metadata with: 
```
curl -X "GET" "https://api.osf.io/v2/files/kzay8/"
```

And if we just want the file, this can be done with: 
```
curl -L https://osf.io/download/kzay8/
```

This requires knowing the ID of the file. We can get this by requesting information from each node. For example, the ID of the root PROTEUS node on OSF is "8dumn"...
```
 curl -X "GET" "https://api.osf.io/v2/nodes/8dumn/children/"
```
...which returns metadata, including the IDs, of each child node. E.g. the folder containing spectral files.

**Comment by nichollsh** [comment]
@lsoucasse @timlichtenberg thoughts on this ^ ?

**Comment by lsoucasse** [comment]
It is nice to be able to directly interact with OSF with the curl command.

We might still consider having python functions that download OSF files and setup data repository so that they can be accessed through the python package. But it can be a python function that runs a shell script as a subprocess. I have looked into the OSF Python Library and it is not straightforward to use.

In any case, we need to agree on a flexible repository structure such that the access to input data is stable and not disturbed by the addition of new files.

**Comment by nichollsh** [comment]
I agree. It is important that things do not move around too much. OSF [supports file revisions](https://help.osf.io/article/282-file-revisions-and-version-control), so even if we update one of the files they should retain the same IDs.

Calling a script as a subprocess makes sense. Should this be part of the pip install step? Or maybe a check when the codes are first run?

**Comment by lsoucasse** [comment]
If it is part of the pip install the data are downloaded with the package and we want to avoid that.

I see it more like a function that the user call to download basic data but still has the freedom to setup is own data repository. We can of course put a check with warning if the data repository is empty.

**Comment by nichollsh** [comment]
That sounds good to me. Let's do that. We should avoid duplicating scripts, since it could easily lead to incorrect file IDs.

In terms of which files are where, maybe something like this:
- SOCRATES
  - Spectral files
  - Other opacity data
- MORS
  - Spada+13 evolution tracks 
  - Stellar spectra
- JANUS 
  - Example results
- PROTEUS 
  - Example results 
- SPIDER 
  - Lookup data

**Comment by timlichtenberg** [comment]
> If it is part of the pip install the data are downloaded with the package and we want to avoid that.
> 
> I see it more like a function that the user call to download basic data but still has the freedom to setup is own data repository. We can of course put a check with warning if the data repository is empty.

To double check this: do you mean that a typical installation would have no data at all, or comes pre-packaged with only minimal necessary data, and the additional data (e.g., higher spectral file resolution) can be downloaded as an additional step if necessary? If the latter that seems fine for me.

**Comment by djbower** [comment]
I think FastChem has a similar model, where enough data are provided to run basic models. And then other (larger) data are available to download.

I wonder if it's possible to allow a 'pip install' like option to also download data? So hypothetically the user could do something like: 

Pip install Proteus --no-data
Pip install Proteus --minimum-data
Pip install Proteus --all-data

You get the idea. Maybe the data sits in a separate repo but an easy install approach that ensures the code can access the data with minimal user configuration is of course preferred.

**Comment by lsoucasse** [comment]
My idea was that packages come with no data but provide a function (or a script accessible through a command line) to download basic data, full data or even a particular file. But if what is suggesting Dan is possible, it would be great too. 

We could opt for the intermediate option where basic data are part of the package and large data sets have to be downloaded but we may end up with data stored in different places which can be difficult to access/maintain.

I also like the idea that you can easily access your data repository from your Desktop so that you can manually add new input data files.

**Comment by lsoucasse** [comment]
Mors and Janus both download and use data stored in the OSF platform now.
