### ISSUE TITLE
Set up automated tests via Github Actions

### ISSUE THREAD

**Issue by timlichtenberg** [FormingWorlds/PROTEUS#86]
Optimally, all newly introduced modules and functions should be automatically tested with every pull request. We will start to continuously work these in, also for older parts of the code that are not being tested as of yet.

See https://docs.github.com/en/actions.

Connected to: FormingWorlds/PROTEUS#71, FormingWorlds/PROTEUS#83

**Comment by timlichtenberg** [comment]
First test for JANUS: #51

**Comment by nichollsh** [comment]
For the model to be tested, there will also need to be a pipeline for configuration it via the GitHub actions framework. This might mean an action for compiling SOCRATES, and another for configuring conda. These aren't physical tests, and aren't as useful, but will also need to be done.

**Comment by timlichtenberg** [comment]
This sounds good to me, we should do this anyway to ensure that SOCRATES can indeed by meaningfully compiled and conda configured. Any tips on that @lsoucasse and @stefsmeets?

**Comment by nichollsh** [comment]
On this topic, I've tried to streamline SOCRATES compilation in AGNI which requires only running two scripts. We could copy this exactly in JANUS.

**Comment by lsoucasse** [comment]
We now have GH actions for Janus, Socrates and Agni. Tests of the PROTEUS framework will be setup at a later stage so I move this issue to TBD.

**Comment by stefsmeets** [comment]
Is there any basic example script that we could reuse for this?
