### ISSUE TITLE
Name of future PyPI packages

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/PROTEUS#91]
Proteus, janus or mors are already names for other PyPI packages. We need to think of a name extension that links to the group or the field of planetary modelling, for instance proteus-kapteyn or proteus-formingworlds.

**Comment by timlichtenberg** [comment]
Thanks, I do think that `fwl-` ultimately makes sense and is economical. This gives us in the future the option to have less headache with naming choice even for more common names or acronyms. So `fwl-proteus`, `fwl-janus`, `fwl-mors` and so on.

**Comment by timlichtenberg** [comment]
Ah, and I think it should be `fwl`, as `fw` seems inadvisable as an acronym. 🙃

**Comment by nichollsh** [comment]
I agree that the `fwl-` prefix makes sense. Can we claim these names now, without configuring the PyPi projects beyond that?

**Comment by lsoucasse** [comment]
I am afraid we cannot reserve the names unless we upload now empty dump ones we complete later. But it seems unlikely that someone will create a fwl-proteus package?

**Comment by lsoucasse** [comment]
We agreed on the naming so I just close this issue.
