### ISSUE TITLE
Remove Sciath submodule

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#92]
This submodule is ostensibly required by SPIDER in order to perform its tests. However, it's possible to run the tests without having to install this extra package. I assume it would also not be integrated into the SPIDER replacement (Aragog).

**Comment by djbower** [comment]
Correct, I would remove from future consideration.  Aragog will just use pytest.

**Comment by nichollsh** [comment]
Sounds good!

**Comment by nichollsh** [comment]
Mistakenly closed the issue - reopened until implemented.
